apiVersion: v1
kind: Service
metadata:
  name: service3
  labels:
    app.kubernetes.io/name: demo
    app.kubernetes.io/instance: service3
spec:
  type: NodePort
  ports:
    - protocol: TCP
      port: 20223
      targetPort: 20223