apiVersion: v1
kind: Service
metadata:
  labels:
    app: vote
  name: vote
spec:
  type: NodePort
  ports:
  - name: "vote-service"
    port: 5000
    targetPort: 80
  selector:
    app: vote
    version: rc-origin
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: vote
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - host: vote-e2e-10x-$Namespace$.ko.coderover.cn
    http:
      paths:
      - path: /
        backend:
          serviceName: vote
          servicePort: 5000