apiVersion: v1
kind: Service
metadata:
  name: frontend
  labels:
    app.kubernetes.io/instance: frontend
    app.kubernetes.io/name: demo
spec:
  type: NodePort
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80