{{- if .Values.registryConf -}}
apiVersion: v1
data:
  .dockercfg: {{ .Values.registryConf }}
kind: Secret
metadata:
  name: {{ .Values.imagePullSecretsName }}
type: kubernetes.io/dockercfg

{{- end -}}