apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.fullnameOverride }}
  labels:
    app.kubernetes.io/name: demo
    app.kubernetes.io/instance: {{ .Values.fullnameOverride }}
spec:
  selector:
    app.kubernetes.io/name: demo
    app.kubernetes.io/instance: {{ .Values.fullnameOverride }}
  type: NodePort
  ports:
    - protocol: TCP
      port: {{ .Values.port }}
      targetPort: {{ .Values.port }}