apiVersion: v1
kind: Service
metadata:
  name: service2
  labels:
    app.kubernetes.io/name: demo
    app.kubernetes.io/instance: service2
spec:
  type: NodePort
  ports:
    - protocol: TCP
      port: 20222
      targetPort: 20222