apiVersion: v1
kind: Service
metadata:
  name: service1
  labels:
    app.kubernetes.io/name: demo
    app.kubernetes.io/instance: service1
spec:
  type: NodePort
  ports:
    - protocol: TCP
      port: 20221
      targetPort: 20221